### ISSUE TITLE
    callbacks += [TrainEpisodeLogger(log_filename)] TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by AIMads** [jakegrigsby/AdvancedPacmanDQNs#1]
Hey tried too run the vanilla agent and got this error, and can't seem too figure out the problem, got here from your article, very interresting findings! What hardware did you train it on? Kind regards Mads

**Comment by jakegrigsby** [comment]
That should be fixed by now. My fork of keras-rl has gone through a lot of changes as I've worked on getting all of this merged; it was probably missing the TrainEpisodeLogger csv dump when you last tried it (or you were using the master version, which is definitely missing that feature). Sorry for the mess. The [current version](https://github.com/jakegrigsby/keras-rl/tree/n-step-dqn) should work fine.

It was trained on a cloud GPU (P4000) with the bigger model clocking in at around 20 hrs/10mm steps.

**Comment by AIMads** [comment]
Thank you very much!!!

Hent Outlook til Android<https://aka.ms/ghei36>




On Tue, Aug 28, 2018 at 11:53 PM +0200, "Jake Grigsby" <notifications@github.com<mailto:notifications@github.com>> wrote:


That should be fixed by now. My fork of keras-rl has gone through a lot of changes as I've worked on getting all of this merged; it was probably missing the TrainEpisodeLogger csv dump when you last tried it (or you were using the master version, which is definitely missing that feature). Sorry for the mess. The current version<https://github.com/jakegrigsby/keras-rl/tree/n-step-dqn> should work fine.

It was trained on a cloud GPU (P4000) with the bigger model clocking in at around 20 hrs/10mm steps.
